version: '3.7'

services:
  database_podhub:
    image: postgres
    container_name: database_podhub
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=podhub
      - POSTGRES_DB=podhub
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: podhub-server
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
